#!/bin/bash

unset CMD
PRE_CWD=`pwd`
cd `dirname $0`/x2swbin
BINDIR=`pwd`
export PATH=$BINDIR:$BINDIR/lib:$PATH

# Pango modules are bundled (for fonts rendering), have to use custom RC that points to them
export PANGO_RC_FILE=./pango/pangorc

PREFIX=nohup
SUFFIX='</dev/null 2>/dev/null 1>&2 &'
TOSTART=$1
shift
if [ "$TOSTART" == "console" ]; then 
  TOSTART=$1
  shift
  PREFIX=
  SUFFIX=
fi
if [ "$TOSTART" == "" ]; then
  TOSTART=pronterface
fi
OPTIONS=$*

case $TOSTART in
  pronterface)
    CMD="$PREFIX ./$TOSTART $OPTIONS $SUFFIX"
    ;;
  slic3r)
    CMD="$PREFIX ./slic3r/$TOSTART $OPTIONS $SUFFIX"
    ;;
  skeinforge)
    CMD="$PREFIX ./python ./skeinforge/skeinforge_application/skeinforge.py $OPTIONS $SUFFIX"
    ;;
  *)
    SCRIPT_NAME=`basename $0`
    echo "Usage: $SCRIPT_NAME [console] [pronterface|slic3r|skeinforge] ..."
    echo "The script invokes the X2SW software bundle components."
    echo "If \"console\" is specified the console stays attached and the output is not supressed."
    echo "The options to pass to the specified subcommand application can be added at the end of the command line."
    echo "If run without paramaters \"pronterface\" is invoked."
    ;;
esac

eval $CMD

cd $PRE_CWD > /dev/null

